[project]
name = "elpris"
version = "0.1.0"
description = "Simpel Python kode der kan fortælle os hvad prisen er på strøm i Danmark lige nu, samt give os en graf over elprisens udvikling"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "duckdb>=1.3.2",
    "ipykernel>=6.29.5",
    "matplotlib>=3.10.0",
    "pydantic>=2.12.0",
    "pytz>=2025.1",
    "requests>=2.32.3",
    "tzlocal>=5.3.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "marimo>=0.17.8",
    "pytest>=8.4.2",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["elpris"]
exclude = ["tests*", "temp*"]
